// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAeFRe_C9c8W-EMRt6zPuBWLA3AtISwX5s',
    appId: '1:26583181497:web:5352c13dacd00565ad5368',
    messagingSenderId: '26583181497',
    projectId: 'galerie-images',
    authDomain: 'galerie-images.firebaseapp.com',
    storageBucket: 'galerie-images.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB1Nhz1ag54rVCsCIT6YevZv16CkKSW07g',
    appId: '1:26583181497:android:2aac1a36921eb134ad5368',
    messagingSenderId: '26583181497',
    projectId: 'galerie-images',
    storageBucket: 'galerie-images.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAcQySNWwPEXlzDnwuvpXFRLd0Ja6h24vI',
    appId: '1:26583181497:ios:9cc7240285cbab9aad5368',
    messagingSenderId: '26583181497',
    projectId: 'galerie-images',
    storageBucket: 'galerie-images.appspot.com',
    iosClientId: '26583181497-gthtia5rplq8f0kudj9kejbd971ra7um.apps.googleusercontent.com',
    iosBundleId: 'com.example.gallerieImages',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAcQySNWwPEXlzDnwuvpXFRLd0Ja6h24vI',
    appId: '1:26583181497:ios:9cc7240285cbab9aad5368',
    messagingSenderId: '26583181497',
    projectId: 'galerie-images',
    storageBucket: 'galerie-images.appspot.com',
    iosClientId: '26583181497-gthtia5rplq8f0kudj9kejbd971ra7um.apps.googleusercontent.com',
    iosBundleId: 'com.example.gallerieImages',
  );
}
